version: '3.9'

services:

  public_data_database:
    image: postgres:latest
    container_name: PublicDataDatabase
    environment:
      POSTGRES_USER: public_user
      POSTGRES_PASSWORD: public_password
      POSTGRES_DB: public_db
    volumes:
      - public_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  medical_data_database:
    image: postgres:latest
    container_name: MedicalDataDatabase
    environment:
      POSTGRES_USER: medical_user
      POSTGRES_PASSWORD: medical_password
      POSTGRES_DB: medical_db
    volumes:
      - medical_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  correlation_database:
    image: postgres:latest
    container_name: CorrelationDatabase
    environment:
      POSTGRES_USER: correlation_user
      POSTGRES_PASSWORD: correlation_password
      POSTGRES_DB: correlation_db
    volumes:
      - correlation_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  public_data:
  medical_data:
  correlation_data:
