version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-benchmark
    platform: linux/amd64 
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
    ports:
      - "3307:3306"
    networks:
      - benchnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  benchnet:
    driver: bridge